import './tracker-column-octave.js?revision=r190-column-octave';
import { createToneRuntime } from './tone-runtime-ties.js?revision=r186-note-ties';
import { createDrumRuntime } from './drum-runtime.js?revision=r184-score-v2';
import { model, buildSong, C, HITS, VOICES } from './tracker-core.js?revision=r187-music-tracker';
let audio=null, play=null, demo={key:'',i:0,t:0};
const DEMO_OCT={lead:{lead:5,picked:5,pluck:5,whistle:5,pulse:5,brass:4,organ:4,reed:4,bell:5,neon:5},bass:{warm:2,upright:2,sub:1,drone:2,drive:2,synth:2},arp:{soft:4,mandolin:4,glass:5,organ:4,metal:4,neon:4}};
function graph(){if(audio)return audio;const AC=globalThis.AudioContext||globalThis.webkitAudioContext;if(!AC)throw Error('Web Audio is not available.');const ctx=new AC({latencyHint:'interactive'}),gain=new GainNode(ctx,{gain:.46}),comp=ctx.createDynamicsCompressor();gain.connect(comp);comp.connect(ctx.destination);const nb=ctx.createBuffer(1,ctx.sampleRate,ctx.sampleRate),data=nb.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;let ss=.125;const PC={C:0,'C#':1,Db:1,D:2,'D#':3,Eb:3,E:4,F:5,'F#':6,Gb:6,G:7,'G#':8,Ab:8,A:9,'A#':10,Bb:10,B:11},freq=n=>{const m=/^([A-G](?:#|b)?)(-?\d+)$/.exec(n||'');if(!m)return 440;const midi=PC[m[1]]+(+m[2]+1)*12;return 440*2**((midi-69)/12)};audio={ctx,tones:createToneRuntime({context:ctx,masterGain:gain,noteToFrequency:freq,getStepSeconds:()=>ss}),drums:createDrumRuntime({context:ctx,masterGain:gain,noiseBuffer:nb}),step:v=>ss=v};return audio}
async function resume(){const g=graph();if(g.ctx.state!=='running')await g.ctx.resume();return g}
export function stopPlayback(){if(play)clearTimeout(play.timer);play=null;if(audio){audio.tones.stop();audio.drums.stop()}document.getElementById('playStatus').textContent='Stopped'}
export async function startPlayback(mode,part=model.state.part,bar=0){stopPlayback();const so=buildSong(),g=await resume(),ss=(60/so.bpm)/4;g.step(ss);const seq=mode==='song'?[...so.arrangement]:[so.sections.find(x=>x.name===part)];play={mode,part,so,seq,si:0,st:mode==='part'?bar*16:0,t:g.ctx.currentTime+.05,ss,timer:0};document.getElementById('playStatus').textContent=mode==='song'?`Playing ${so.name}`:`Playing ${C[part]}`;tick()}
function tick(){if(!play)return;const g=audio,s=model.state;while(play&&play.t<g.ctx.currentTime+.12){const sec=play.seq[play.si],i=play.st,t=play.t;if(s.channels.lead)g.tones.playLead(sec.lead[i],t,sec.leadVoice);if(s.channels.bass)g.tones.playBass(sec.bass[i],t,sec.bassVoice);if(s.channels.arp)g.tones.playArp(sec.arp[i],t,sec.arpVoice);if(s.channels.drums)g.drums.play(sec.drums[i],t,sec.drumKit);const sw=+play.so.swing||0;play.t+=play.ss*(i%2===0?1+sw:1-sw);play.st++;if(play.st>=sec.lead.length){play.st=0;play.si++;if(play.si>=play.seq.length){if(s.loop)play.si=0;else{play=null;document.getElementById('playStatus').textContent='Stopped';return}}}}if(play)play.timer=setTimeout(tick,25)}
export function isPlaying(){return Boolean(play)}
export async function demoInstrument(group,name,button){stopPlayback();const g=await resume();g.step(.16);const now=performance.now(),key=`${group}:${name}`;demo.i=demo.key!==key||now-demo.t>3000?0:(demo.i+1)%8;demo.key=key;demo.t=now;document.querySelectorAll('.demo-button').forEach(b=>b.classList.toggle('active',b===button));if(group==='drums'){const h=HITS[demo.i];g.drums.play(h,g.ctx.currentTime+.02,name);document.getElementById('demoStatus').textContent=`${name} · ${h}`;return}const oct=DEMO_OCT[group]?.[name]??(group==='bass'?2:4),notes=['C','D','E','F','G','A','B','C'],sol=['DO','RE','MI','FA','SOL','LA','TI','DO'],note=`${notes[demo.i]}${oct+(demo.i===7?1:0)}`;g.tones[`play${group[0].toUpperCase()+group.slice(1)}`](note,g.ctx.currentTime+.02,name);document.getElementById('demoStatus').textContent=`${name} · ${sol[demo.i]} · ${note}`}
export function renderDemos(){const root=document.getElementById('instrumentDemos');for(const [group,lib] of Object.entries(VOICES)){const w=document.createElement('div');w.className='demo-group';w.innerHTML=`<h3>${group==='arp'?'ARP / TEXTURE':group.toUpperCase()}</h3>`;const bs=document.createElement('div');bs.className='demo-buttons';Object.keys(lib).forEach(name=>{const b=document.createElement('button');b.type='button';b.className='demo-button';b.textContent=name;b.onclick=()=>demoInstrument(group,name,b);bs.append(b)});w.append(bs);root.append(w)}}
