import { SONGBOOK } from './songbook.js?revision=r185-menu-orchestration';
import { LEAD_VOICES, BASS_VOICES, ARP_VOICES, DRUM_KITS } from './instrument-bank.js?revision=r184-score-v2';
import { bars, makeSection, makeSong } from './song-tools.js?revision=r186-note-ties';

export const N=['tune','bridge','chorus'];
export const C={tune:'T',bridge:'B',chorus:'C'};
export const L=['lead','bass','arp','drums'];
export const P=['lead','bass','arp'];
export const HITS=['K','S','H','O','C','T','M','R'];
export const VOICES={lead:LEAD_VOICES,bass:BASS_VOICES,arp:ARP_VOICES,drums:DRUM_KITS};
export { SONGBOOK, LEAD_VOICES, BASS_VOICES, ARP_VOICES, DRUM_KITS };
const STORE='turn-music-tracker-draft-v1', NOTE=/^[A-G](?:#|b)?-?\d+$/, DRUM=/^[KSCTMRHO]+$/;
const blank=(name,b=4)=>({name,harmony:Array(b).fill(''),leadVoice:'lead',bassVoice:'warm',arpVoice:'soft',drumKit:'classic',lead:Array(b*16).fill(null),bass:Array(b*16).fill(null),arp:Array(b*16).fill(null),drums:Array(b*16).fill(null)});
const fresh=()=>({meta:{id:'new-song',name:'New TURN Song',bpm:120,key:'C major',style:'',swing:0},arrangement:['tune','tune','tune','bridge','chorus','chorus'],parts:{tune:blank('tune'),bridge:blank('bridge'),chorus:blank('chorus')},part:'tune',bar:0,sel:{lane:'lead',row:0},oct:{lead:5,bass:2,arp:4},channels:{lead:true,bass:true,arp:true,drums:true},loop:true,filename:'new-song.js'});
const slug=v=>(String(v||'song').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'song');
let state=fresh(), saveTimer=0;
export const model={get state(){return state},fresh(){state=fresh();return state},set(x){state=x;return state},barsIn(p=state.parts[state.part]){return p.lead.length/16},step(){return state.bar*16+state.sel.row},slug};
export function save(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>{try{localStorage.setItem(STORE,JSON.stringify(state))}catch(_){}},180)}
export function restore(){try{const x=JSON.parse(localStorage.getItem(STORE)||'null');if(x?.parts?.tune&&x?.parts?.bridge&&x?.parts?.chorus){state=x;return true}}catch(_){}return false}
function expand(a){const o=Array(a.length).fill(null);a.forEach((v,i)=>{if(v&&typeof v==='object'&&v.note){o[i]=v.note;for(let j=1;j<(v.heldSteps||1)&&i+j<o.length;j++)o[i+j]='='}else o[i]=v||null});return o}
export function fromSong(song){const x=fresh();x.meta={id:song.id,name:song.name,bpm:song.bpm,key:song.key||'',style:song.style||'',swing:song.swing||0};x.arrangement=[...song.form];for(const q of song.sections)if(x.parts[q.name])x.parts[q.name]={name:q.name,harmony:[...q.harmony],leadVoice:q.leadVoice,bassVoice:q.bassVoice,arpVoice:q.arpVoice,drumKit:q.drumKit,lead:expand(q.lead),bass:expand(q.bass),arp:expand(q.arp),drums:q.drums.map(v=>v||null)};x.filename=`${slug(song.id)}.js`;state=x;return x}
export function validToken(lane,v,i,p){if(v==null)return true;if(lane==='drums')return DRUM.test(v);if(v==='=')return i>0&&(p[lane][i-1]==='='||NOTE.test(p[lane][i-1]||''));return NOTE.test(v)}
export function errors(){const e=[];if(!state.meta.id.trim())e.push('Song ID is required.');if(!state.meta.name.trim())e.push('Song name is required.');if(!(state.meta.bpm>=70&&state.meta.bpm<=180))e.push('BPM must be 70–180.');if(!(state.meta.swing>=0&&state.meta.swing<=.24))e.push('Swing must be 0–0.24.');for(const n of N){const p=state.parts[n],b=model.barsIn(p);if(p.harmony.length!==b)e.push(`${n}: harmony/bar mismatch.`);for(const l of L)for(let i=0;i<p[l].length;i++)if(!validToken(l,p[l][i],i,p))e.push(`${C[n]} ${l} row ${i.toString(16).toUpperCase()}: invalid “${p[l][i]}”.`)}return e}
const barStrings=a=>Array.from({length:a.length/16},(_,b)=>a.slice(b*16,b*16+16).map(v=>v??'-').join(' '));
function section(p){return makeSection({name:p.name,harmony:p.harmony,leadVoice:p.leadVoice,bassVoice:p.bassVoice,arpVoice:p.arpVoice,drumKit:p.drumKit,lead:bars(...barStrings(p.lead)),bass:bars(...barStrings(p.bass)),arp:bars(...barStrings(p.arp)),drums:bars(...barStrings(p.drums))})}
export function buildSong(){const e=errors();if(e.length)throw Error(e[0]);return makeSong({...state.meta,bpm:Number(state.meta.bpm),swing:Number(state.meta.swing),sections:N.map(n=>section(state.parts[n])),arrangement:state.arrangement})}
const q=v=>`'${String(v??'').replace(/\\/g,'\\\\').replace(/'/g,"\\'")}'`;
function sectionJS(k,p){const h=p.harmony.some(Boolean)?` harmony: [${p.harmony.map(q).join(', ')}],`:'';const out=[`const ${k} = makeSection({`,`  name: ${q(p.name)},${h}`,`  leadVoice: ${q(p.leadVoice)}, bassVoice: ${q(p.bassVoice)}, arpVoice: ${q(p.arpVoice)}, drumKit: ${q(p.drumKit)},`];L.forEach((l,li)=>{out.push(`  ${l}: bars(`);barStrings(p[l]).forEach((b,i,a)=>out.push(`    ${q(b)}${i<a.length-1?',':''}`));out.push(`  )${li<L.length-1?',':''}`)});out.push('});');return out.join('\n')}
export function source(){const cn=(state.meta.id.toUpperCase().replace(/[^A-Z0-9]+/g,'_')||'TURN')+'_SONG';return [`import { bars, makeSection, makeSong } from './song-tools.js?revision=r186-note-ties';`,'',sectionJS('TUNE',state.parts.tune),'',sectionJS('BRIDGE',state.parts.bridge),'',sectionJS('CHORUS',state.parts.chorus),'',`export const ${cn} = makeSong({`,`  id: ${q(state.meta.id)}, name: ${q(state.meta.name)}, bpm: ${Number(state.meta.bpm)}, key: ${q(state.meta.key)},`,`  style: ${q(state.meta.style)}, swing: ${Number(state.meta.swing)},`,`  sections: [TUNE, BRIDGE, CHORUS], arrangement: [${state.arrangement.map(q).join(', ')}]`,'});',''].join('\n')}
const strings=x=>[...x.matchAll(/'((?:\\.|[^'\\])*)'|"((?:\\.|[^"\\])*)"/g)].map(m=>(m[1]??m[2]).replace(/\\'/g,"'").replace(/\\"/g,'"').replace(/\\\\/g,'\\'));
const prop=(b,n,d='')=>{const m=new RegExp(`\\b${n}\\s*:\\s*(['"])(.*?)\\1`,'s').exec(b);return m?m[2]:d}, num=(b,n,d=0)=>+(new RegExp(`\\b${n}\\s*:\\s*(-?\\d+(?:\\.\\d+)?)`).exec(b)?.[1]??d);
function lane(block,name){const at=block.search(new RegExp(`\\b${name}\\s*:`)),tail=block.slice(at);let m=new RegExp(`\\b${name}\\s*:\\s*bars\\(([\\s\\S]*?)\\)`).exec(tail);if(m)return strings(m[1]).flatMap(x=>x.trim().split(/\s+/).map(v=>v==='-'?null:v));m=new RegExp(`\\b${name}\\s*:\\s*\\[([\\s\\S]*?)\\]`).exec(tail);if(!m)throw Error(`Missing ${name} lane.`);return m[1].split(',').map(z=>{const t=z.trim();return !t||t==='null'?null:(strings(t)[0]??null)})}
export function parseSource(src){const parts={};for(const m of src.matchAll(/const\s+\w+\s*=\s*makeSection\s*\(\{([\s\S]*?)\}\);/g)){const b=m[1],name=prop(b,'name');if(!N.includes(name))continue;const lead=lane(b,'lead'),bass=lane(b,'bass'),arp=lane(b,'arp'),drums=lane(b,'drums'),count=lead.length/16;if(!Number.isInteger(count)||![bass.length,arp.length,drums.length].every(x=>x===lead.length))throw Error(`${name} lane lengths are invalid.`);const hm=new RegExp(`\\bharmony\\s*:\\s*\\[([\\s\\S]*?)\\]`).exec(b);parts[name]={name,harmony:hm?strings(hm[1]):Array(count).fill(''),leadVoice:prop(b,'leadVoice','lead'),bassVoice:prop(b,'bassVoice','warm'),arpVoice:prop(b,'arpVoice','soft'),drumKit:prop(b,'drumKit','classic'),lead,bass,arp,drums}}for(const n of N)if(!parts[n])throw Error(`Source is missing ${n}.`);let last;for(const m of src.matchAll(/makeSong\s*\(\{([\s\S]*?)\}\);/g))last=m[1];if(!last)throw Error('Source is missing makeSong().');const am=/\barrangement\s*:\s*\[([\s\S]*?)\]/.exec(last),arr=am?strings(am[1]):[];if(arr.length!==6)throw Error('Arrangement must contain six parts.');return{meta:{id:prop(last,'id','imported-song'),name:prop(last,'name','Imported TURN Song'),bpm:num(last,'bpm',120),key:prop(last,'key',''),style:prop(last,'style',''),swing:num(last,'swing',0)},arrangement:arr,parts}}
export function fromParsed(x){state=fresh();state.meta=x.meta;state.arrangement=x.arrangement;state.parts=x.parts;state.filename=`${slug(x.meta.id)}.js`;return state}
export function rawURL(v){try{const u=new URL(v,location.href),p=u.pathname.split('/').filter(Boolean);if(u.hostname==='github.com'&&p[2]==='blob')return `https://raw.githubusercontent.com/${p[0]}/${p[1]}/${p.slice(3).join('/')}`;return u.href}catch(_){return v}}
