import { model, save, restore, fromSong, fromParsed, parseSource, rawURL, errors, source, validToken, SONGBOOK, LEAD_VOICES, BASS_VOICES, ARP_VOICES, DRUM_KITS, N, C, L, P, HITS } from './tracker-core.js?revision=r187-music-tracker';
import { startPlayback, stopPlayback, isPlaying, renderDemos } from './tracker-audio.js?revision=r187-music-tracker';
const $=id=>document.getElementById(id), PAD=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'], SN=PAD;
const KEYS={z:0,s:1,x:2,d:3,c:4,v:5,g:6,b:7,h:8,n:9,j:10,m:11,q:12,'2':13,w:14,'3':15,e:16,r:17,'5':18,t:19,'6':20,y:21,'7':22,u:23};
let clip=null;
const s=()=>model.state, status=(m,k='')=>{ $('draftStatus').textContent=m;$('draftStatus').className=`status-pill${k?' '+k:''}` };
function changed(doSave=true){const e=errors();$('validationOutput').textContent=e.length?e.join('\n'):'Ready.';$('exportPreview').value=source();if(e.length)status(`${e.length} validation issue${e.length===1?'':'s'}`,'bad');else if(doSave)status('Ready','good');if(doSave)save()}
function renderMeta(){for(const [id,k] of [['metaId','id'],['metaName','name'],['metaBpm','bpm'],['metaKey','key'],['metaStyle','style'],['metaSwing','swing']])$(id).value=s().meta[k];$('filenameInput').value=s().filename}
function renderArr(){const r=$('arrangementControls');r.replaceChildren();s().arrangement.forEach((v,i)=>{const x=document.createElement('select');x.setAttribute('aria-label',`Arrangement part ${i+1}`);N.forEach(n=>x.add(new Option(C[n],n,false,n===v)));x.onchange=()=>{s().arrangement[i]=x.value;renderArr();changed()};r.append(x)});$('arrangementText').value=s().arrangement.map(n=>C[n]).join('')}
function renderPart(){document.querySelectorAll('.part-tab').forEach(b=>{const a=b.dataset.part===s().part;b.classList.toggle('active',a);b.setAttribute('aria-selected',String(a))});const p=s().parts[s().part];$('leadVoice').value=p.leadVoice;$('bassVoice').value=p.bassVoice;$('arpVoice').value=p.arpVoice;$('drumKit').value=p.drumKit;s().bar=Math.min(s().bar,model.barsIn(p)-1);$('barPosition').textContent=`Bar ${s().bar+1} / ${model.barsIn(p)}`;$('barHarmony').value=p.harmony[s().bar]||'';$('removeBarButton').disabled=model.barsIn(p)<=1}
function renderGrid(){const root=$('trackerGrid'),p=s().parts[s().part];root.replaceChildren();for(let row=0;row<16;row++){const i=s().bar*16+row,d=document.createElement('div');d.className=`tracker-row${row%4===0?' beat':''}${row===s().sel.row?' current':''}`;const num=document.createElement('div');num.className='row-number';num.textContent=i.toString(16).toUpperCase().padStart(2,'0');d.append(num);for(const l of L){const x=document.createElement('input');x.className='step-input'+(validToken(l,p[l][i],i,p)?'':' invalid');x.dataset.lane=l;x.dataset.row=row;x.value=p[l][i]??'-';x.spellcheck=false;x.maxLength=l==='drums'?8:4;x.setAttribute('aria-label',`${s().part} bar ${s().bar+1} row ${num.textContent} ${l}`);x.onfocus=()=>{s().sel={lane:l,row};renderPad()};x.onchange=()=>commit(x,false);x.onkeydown=keyDown;d.append(x)}root.append(d)}renderPad()}
function renderPad(){const pitched=P.includes(s().sel.lane);$('selectedCellLabel').textContent=`${C[s().part]} · ${s().sel.lane} · row ${model.step().toString(16).toUpperCase().padStart(2,'0')}`;$('octaveControl').hidden=!pitched;$('noteButtons').hidden=!pitched;$('drumButtons').hidden=pitched;if(pitched)$('entryOctave').value=s().oct[s().sel.lane]}
function render(){renderMeta();renderArr();renderPart();renderGrid();document.querySelectorAll('[data-channel]').forEach(x=>x.checked=s().channels[x.dataset.channel]!==false);$('loopPlayback').checked=s().loop!==false;changed(false)}
function commit(x,advance){const l=x.dataset.lane,row=+x.dataset.row,p=s().parts[s().part],i=s().bar*16+row;let v=x.value.trim();v=!v||v==='-'?null:v==='='?'=':l==='drums'?v.toUpperCase():v[0].toUpperCase()+v.slice(1);p[l][i]=v;x.value=v??'-';x.classList.toggle('invalid',!validToken(l,v,i,p));changed();if(advance)move(0,1)}
function focus(l,row){s().sel={lane:l,row};requestAnimationFrame(()=>{const x=document.querySelector(`.step-input[data-lane="${l}"][data-row="${row}"]`);x?.focus();x?.select()})}
function move(dl,dr){let li=L.indexOf(s().sel.lane)+dl,r=s().sel.row+dr;if(r<0&&s().bar>0){s().bar--;r=15;renderPart();renderGrid()}else if(r>15&&s().bar<model.barsIn()-1){s().bar++;r=0;renderPart();renderGrid()}r=Math.max(0,Math.min(15,r));focus(L[Math.max(0,Math.min(3,li))],r)}
function keyDown(e){const x=e.currentTarget,l=x.dataset.lane;if(e.key==='ArrowUp'){e.preventDefault();move(0,-1)}else if(e.key==='ArrowDown'){e.preventDefault();move(0,1)}else if(e.key==='Enter'){e.preventDefault();commit(x,true)}else if(e.key==='-'||(e.key==='='&&l!=='drums')){e.preventDefault();x.value=e.key;commit(x,true)}else if(P.includes(l)&&!e.metaKey&&!e.ctrlKey&&!e.altKey&&KEYS[e.key.toLowerCase()]!=null){e.preventDefault();const z=KEYS[e.key.toLowerCase()],o=s().oct[l]+Math.floor(z/12);x.value=`${SN[z%12]}${o}`;commit(x,true)}else if(e.altKey&&e.key==='ArrowLeft'){e.preventDefault();move(-1,0)}else if(e.altKey&&e.key==='ArrowRight'){e.preventDefault();move(1,0)}}
function quick(v){const x=document.querySelector(`.step-input[data-lane="${s().sel.lane}"][data-row="${s().sel.row}"]`);if(x){x.value=v;commit(x,true)}}
function padButtons(){const a=$('noteButtons');PAD.forEach(n=>{const b=document.createElement('button');b.type='button';b.className='note-button'+(n.includes('#')?' accidental':'');b.textContent=n;b.onclick=()=>quick(`${n}${s().oct[s().sel.lane]}`);a.append(b)});[['REST','-'],['TIE','='],['CLEAR','']].forEach(([n,v])=>{const b=document.createElement('button');b.type='button';b.className='note-button special';b.textContent=n;b.onclick=()=>quick(v);a.append(b)});const d=$('drumButtons');HITS.forEach(h=>{const b=document.createElement('button');b.type='button';b.className='note-button';b.textContent=h;b.onclick=()=>{const p=s().parts[s().part],i=model.step(),set=new Set((p.drums[i]||'').split(''));set.has(h)?set.delete(h):set.add(h);p.drums[i]=HITS.filter(x=>set.has(x)).join('')||null;renderGrid();changed()};d.append(b)});const adv=document.createElement('button');adv.type='button';adv.className='note-button special';adv.textContent='ADVANCE ↓';adv.onclick=()=>move(0,1);d.append(adv)}
function addBar(){const p=s().parts[s().part];if(model.barsIn(p)>=16)return status('Editor limit: 16 bars per part','bad');L.forEach(l=>p[l].push(...Array(16).fill(null)));p.harmony.push('');s().bar=model.barsIn(p)-1;renderPart();renderGrid();changed()}
function removeBar(){const p=s().parts[s().part];if(model.barsIn(p)<=1)return;const i=s().bar*16;L.forEach(l=>p[l].splice(i,16));p.harmony.splice(s().bar,1);s().bar=Math.min(s().bar,model.barsIn(p)-1);renderPart();renderGrid();changed()}
function copyBar(){const p=s().parts[s().part],i=s().bar*16;clip={harmony:p.harmony[s().bar],...Object.fromEntries(L.map(l=>[l,p[l].slice(i,i+16)]))};status('Bar copied','good')}
function pasteBar(){if(!clip)return status('Copy a bar first','bad');const p=s().parts[s().part],i=s().bar*16;L.forEach(l=>p[l].splice(i,16,...clip[l]));p.harmony[s().bar]=clip.harmony;renderPart();renderGrid();changed()}
function clearBar(){const p=s().parts[s().part],i=s().bar*16;L.forEach(l=>p[l].fill(null,i,i+16));p.harmony[s().bar]='';renderPart();renderGrid();changed()}
function changeBar(d){s().bar=Math.max(0,Math.min(model.barsIn()-1,s().bar+d));s().sel.row=0;renderPart();renderGrid();save();if(isPlaying())startPlayback('part',s().part,s().bar).catch(e=>status(e.message,'bad'))}
function voiceOptions(){for(const [id,lib] of [['leadVoice',LEAD_VOICES],['bassVoice',BASS_VOICES],['arpVoice',ARP_VOICES],['drumKit',DRUM_KITS]])Object.keys(lib).forEach(n=>$(id).add(new Option(n,n)))}
function download(){if(errors().length)return status(errors()[0],'bad');const b=new Blob([source()],{type:'text/javascript'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=s().filename||`${model.slug(s().meta.id)}.js`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function wire(){const sel=$('songSelect');SONGBOOK.forEach(x=>sel.add(new Option(`${x.name} · ${x.id}`,x.id)));$('loadSongButton').onclick=()=>{fromSong(SONGBOOK.find(x=>x.id===sel.value));render();save();status('Song loaded','good')};$('loadUrlButton').onclick=async()=>{try{status('Fetching…');const r=await fetch(rawURL($('songUrl').value),{credentials:'omit'});if(!r.ok)throw Error(`HTTP ${r.status}`);fromParsed(parseSource(await r.text()));render();save();status('URL imported','good')}catch(e){status(`Import failed: ${e.message}`,'bad')}};$('readClipboardButton').onclick=async()=>{try{const t=await navigator.clipboard.readText();$('pasteSource').value=t;fromParsed(parseSource(t));render();save();status('Clipboard imported','good')}catch(_){status('Clipboard read blocked; paste into the box instead.','bad')}};$('loadPasteButton').onclick=()=>{try{fromParsed(parseSource($('pasteSource').value));render();save();status('Pasted source imported','good')}catch(e){status(`Import failed: ${e.message}`,'bad')}};$('newSongButton').onclick=()=>{stopPlayback();model.fresh();render();save()};$('copySourceButton').onclick=async()=>{try{if(errors().length)throw Error(errors()[0]);await navigator.clipboard.writeText(source());status('Copied .js','good')}catch(e){status(e.message,'bad')}};$('downloadSourceButton').onclick=download;$('filenameInput').oninput=e=>{s().filename=e.target.value;save()};for(const [id,k,cast] of [['metaId','id',String],['metaName','name',String],['metaBpm','bpm',Number],['metaKey','key',String],['metaStyle','style',String],['metaSwing','swing',Number]])$(id).oninput=e=>{s().meta[k]=cast(e.target.value);changed()};document.querySelectorAll('.part-tab').forEach(b=>b.onclick=()=>{s().part=b.dataset.part;s().bar=0;s().sel.row=0;renderPart();renderGrid();save()});for(const [id,k] of [['leadVoice','leadVoice'],['bassVoice','bassVoice'],['arpVoice','arpVoice'],['drumKit','drumKit']])$(id).onchange=e=>{s().parts[s().part][k]=e.target.value;changed()};$('barHarmony').oninput=e=>{s().parts[s().part].harmony[s().bar]=e.target.value;changed()};$('prevBarButton').onclick=()=>changeBar(-1);$('nextBarButton').onclick=()=>changeBar(1);$('addBarButton').onclick=addBar;$('removeBarButton').onclick=removeBar;$('copyBarButton').onclick=copyBar;$('pasteBarButton').onclick=pasteBar;$('clearBarButton').onclick=clearBar;$('entryOctave').oninput=e=>{if(P.includes(s().sel.lane))s().oct[s().sel.lane]=+e.target.value};$('playSongButton').onclick=()=>startPlayback('song').catch(e=>status(e.message,'bad'));document.querySelectorAll('.part-play').forEach(b=>b.onclick=()=>startPlayback('part',b.dataset.part,b.dataset.part===s().part?s().bar:0).catch(e=>status(e.message,'bad')));$('stopButton').onclick=stopPlayback;$('loopPlayback').onchange=e=>{s().loop=e.target.checked;save()};document.querySelectorAll('[data-channel]').forEach(x=>x.onchange=()=>{s().channels[x.dataset.channel]=x.checked;save()})}
voiceOptions();padButtons();renderDemos();restore();render();wire();
