/* TURN offline service worker (#1030). One worker for /turn/ and, imported by
   /turn-next/sw.js, for /turn-next/: names and lists follow the registration scope.

   - Install: precache the release's files (offline-precache.json, generated by
     release.mjs), eight at a time, resuming if a previous install stopped midway.
     A file that fails fails the install, so the previous release stays in charge.
     The first install tells open pages how far it has come (turn-offline-progress).
   - Online, TURN behaves as before: the network answers first, so a new build shows
     up at once, and each answer is kept (by its exact URL, build key included).
   - Offline, on a network that stalls, or when the server answers with an error: the
     kept answer for the exact URL, else the release's precached file for that path.
   - Third-party models pinned to a commit never change: cache first, kept for good.
   - Other pages in the app come from the network; offline, one never opened says so.
   - Activate: drop the previous release's caches and take over open pages. */

const RELEASE = '20261001-r352';
const SCOPE = new URL(self.registration.scope).pathname;
const NAME = SCOPE.replace(/\//g, '') || 'turn';
const PRECACHE = `${NAME}-precache-${RELEASE}`;
const RUNTIME = `${NAME}-runtime-${RELEASE}`;
const EXTERNAL = 'turn-external-v1';
const STATUS_KEY = `${SCOPE}__offline-status`;
const NAVIGATION_TIMEOUT_MS = 4000;
const RESOURCE_TIMEOUT_MS = 8000;
const BATCH = 8;
const PINNED_EXTERNAL = [
  /^https:\/\/cdn\.jsdelivr\.net\/gh\/[^/]+\/[^/@]+@[0-9a-f]{40}\//,
  /^https:\/\/raw\.githubusercontent\.com\/[^/]+\/[^/]+\/[0-9a-f]{40}\//
];
const TIMED_OUT = Symbol('timed out');
const FAILED = Symbol('failed');

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(PRECACHE);
    const list = await (await fetch(`${SCOPE}offline-precache.json?build=${RELEASE}`, { cache: 'no-cache' })).json();
    const total = list.files.length;
    // Only the first install: an update downloads quietly, the release in charge still plays offline.
    const first = !self.registration.active;
    let failed = 0;
    for (let index = 0; index < total; index += BATCH) {
      await Promise.all(list.files.slice(index, index + BATCH).map(async (file) => {
        if (await cache.match(file)) return;
        try {
          const response = await fetch(file, { cache: 'no-cache' });
          if (response.ok) await cache.put(file, response);
          else failed += 1;
        } catch {
          failed += 1;
        }
      }));
      if (first) await report({ stored: Math.min(index + BATCH, total), total });
    }
    // Incomplete: keep the previous release and its caches; the next visit resumes.
    if (failed) {
      if (first) await report({ stored: total - failed, total, failed });
      throw new Error(`TURN offline: ${failed} of ${total} files failed to store`);
    }
    const status = { release: RELEASE, files: total, failed };
    await cache.put(STATUS_KEY, new Response(JSON.stringify(status), { headers: { 'content-type': 'application/json' } }));
    await self.skipWaiting();
  })());
});

async function report(progress) {
  for (const client of await self.clients.matchAll({ type: 'window', includeUncontrolled: true })) {
    client.postMessage({ type: 'turn-offline-progress', release: RELEASE, ...progress });
  }
}

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) {
      const ours = key.startsWith(`${NAME}-precache-`) || key.startsWith(`${NAME}-runtime-`);
      if (ours && key !== PRECACHE && key !== RUNTIME) await caches.delete(key);
    }
    await self.clients.claim();
  })());
});

// The page asks how ready offline play is: { release, files, failed } or null.
self.addEventListener('message', (event) => {
  if (event.data?.type !== 'turn-offline-status' || !event.ports?.[0]) return;
  event.waitUntil((async () => {
    const response = await (await caches.open(PRECACHE)).match(STATUS_KEY);
    event.ports[0].postMessage(response ? await response.json() : null);
  })());
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET' || request.headers.has('range')) return;
  const url = new URL(request.url);
  if (url.origin === self.location.origin) {
    if (!url.pathname.startsWith(SCOPE) && !url.pathname.startsWith('/turn/')) return;
    if (request.mode === 'navigate') {
      if (url.pathname === SCOPE || url.pathname === `${SCOPE}index.html`) event.respondWith(navigate(request));
      else if (url.pathname.startsWith(SCOPE)) event.respondWith(otherPage(request));
      return;
    }
    event.respondWith(sameOrigin(request, url));
    return;
  }
  if (PINNED_EXTERNAL.some((pattern) => pattern.test(request.url))) event.respondWith(pinned(request));
});

function race(promise, ms) {
  return Promise.race([
    promise.catch(() => FAILED),
    new Promise((resolve) => setTimeout(resolve, ms, TIMED_OUT))
  ]);
}

function keep(cacheName, key, response) {
  if (!response.ok || response.status !== 200 || response.type !== 'basic') return;
  const copy = response.clone();
  caches.open(cacheName).then((cache) => cache.put(key, copy)).catch(() => {});
}

async function fromCaches(request, url) {
  const exact = await (await caches.open(RUNTIME)).match(request);
  if (exact) return exact;
  const precached = await (await caches.open(PRECACHE)).match(url.pathname);
  if (precached) return precached;
  // A file this release never listed: the newest kept copy for the path, any build.
  return caches.match(request, { ignoreSearch: true });
}

async function sameOrigin(request, url) {
  const network = fetch(request);
  const first = await race(network, RESOURCE_TIMEOUT_MS);
  const answered = first !== FAILED && first !== TIMED_OUT;
  if (answered && first.ok) {
    keep(RUNTIME, request, first);
    return first;
  }
  // No answer, or an error (a deploy in progress, an outage): the kept copy if there is one.
  const cached = await fromCaches(request, url);
  if (cached) {
    if (!answered) network.then((late) => keep(RUNTIME, request, late)).catch(() => {});
    return cached;
  }
  if (answered) return first;
  return first === TIMED_OUT ? network : Response.error();
}

async function navigate(request) {
  const network = fetch(request);
  const first = await race(network, NAVIGATION_TIMEOUT_MS);
  if (first !== FAILED && first !== TIMED_OUT && first.ok) {
    keep(RUNTIME, `${SCOPE}index.html`, first);
    return first;
  }
  const runtime = await caches.open(RUNTIME);
  const cached = (await runtime.match(`${SCOPE}index.html`))
    || (await (await caches.open(PRECACHE)).match(`${SCOPE}index.html`))
    || (await caches.match(`${SCOPE}index.html`, { ignoreSearch: true }));
  if (cached) return cached;
  if (first === TIMED_OUT) return network;
  return first === FAILED ? Response.error() : first;
}

// Other pages in the app (usage statistics, the history reader) are not stored ahead;
// offline, a page that was never opened says so and leads back to the game instead of
// leaving the installed app on a browser error.
async function otherPage(request) {
  let response = null;
  try {
    response = await fetch(request);
  } catch {
    // Offline: below.
  }
  if (response?.ok) {
    keep(RUNTIME, request, response);
    return response;
  }
  const cached = await caches.match(request, { ignoreSearch: true });
  if (cached) return cached;
  return response || new Response(OFFLINE_PAGE, { status: 503, headers: { 'content-type': 'text/html; charset=utf-8' } });
}

const OFFLINE_PAGE = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="theme-color" content="#08090a">
<title>Offline · TURN</title>
<style>
  body { margin: 0; min-height: 100vh; display: grid; place-items: center; padding: max(24px, env(safe-area-inset-top)) 24px max(24px, env(safe-area-inset-bottom));
    box-sizing: border-box; background: #fff8e8; color: #08090a; font: 17px/1.4 system-ui, -apple-system, sans-serif; }
  main { max-width: 26rem; padding: 24px; border: 3px solid #08090a; border-radius: 20px; background: #fffcf2; box-shadow: 8px 8px 0 #08090a; }
  h1 { margin: 0 0 8px; font-size: 1.75rem; font-weight: 900; text-transform: uppercase; }
  p { margin: 0 0 20px; }
  a { display: inline-flex; align-items: center; min-height: 44px; padding: 0 18px; border: 3px solid #08090a; border-radius: 12px;
    background: #ea5da1; box-shadow: 4px 4px 0 #08090a; color: #08090a; font-weight: 900; letter-spacing: 0.04em; text-decoration: none; }
</style>
</head>
<body>
<main>
  <h1>You're offline</h1>
  <p>This page needs a connection. TURN itself works offline: your tracks, cars and records are on this device.</p>
  <a href="${SCOPE}">BACK TO TURN</a>
</main>
</body>
</html>`;

async function pinned(request) {
  const cache = await caches.open(EXTERNAL);
  const hit = await cache.match(request);
  if (hit) return hit;
  const response = await fetch(request);
  if (response.ok && response.status === 200) cache.put(request, response.clone()).catch(() => {});
  return response;
}
